version: '3'
services:
  satisfactory:
    iamge: ghcr.io/cvoegele/satisfactory-docker:main
    restart: always
    ports:
      - 15777:15777/udp
      - 15000:15000/udp
      - 7777:7777/udp
    volumes:
      - ./data:/home/factory-worker/satisfactory-server
