name: Docker Image CI

on:
  schedule:
    - cron:  '30 17 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag factory-server:$(date +%s) --tag factory-server:latest
